name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build pyz
        run: python3 scripts/build_pyz.py
      - name: Smoke test
        run: python3 a2dev_cli.py smoke

